builtin_interfaces/Time stamp

float64 x
float64 y
float64 speed
bool is_pose_accurate

uint8 track_flag
uint8 vehicle_flag
float64 defender_target_speed

bool emergency_stop_cmd

float64 joystick_diff
float64 pose_diff
float64 rc_diff
float64 opp_detections_diff
float64 low_level_fault_diff

uint8 ttl_index
uint8 track_location
float64 distance_from_sf
float64 lap_percentage
uint64 waypoint_index

uint8 num_laps
float64 lap_time

TargetTrajectoryCommand trajectory_command
TspTelemetry tsp_telemetry