builtin_interfaces/Time stamp

#Tire Temp (outside)
float32 lf_inner_temp
float32 lf_middle_temp
float32 lf_outer_temp
float32 lr_inner_temp
float32 lr_middle_temp
float32 lr_outer_temp
float32 rf_inner_temp
float32 rf_middle_temp
float32 rf_outer_temp
float32 rr_inner_temp
float32 rr_middle_temp
float32 rr_outer_temp

#Carcass Temp (inside)
float32 lfc_inner_temp
float32 lfc_middle_temp
float32 lfc_outer_temp
float32 lrc_inner_temp
float32 lrc_middle_temp
float32 lrc_outer_temp
float32 rfc_inner_temp
float32 rfc_middle_temp
float32 rfc_outer_temp
float32 rrc_inner_temp
float32 rrc_middle_temp
float32 rrc_outer_temp