/controller_manager:
  ros__parameters:
    manager:
      debug: true
      control_pub_rate: 50
      plugins:
        - control::longitudinal::PIDLonController
        - control::lateral::PurePursuitController

    longitudinal:
      pid:
        kp: 0.0
        ki: 0.0
        kd: 0.05
        min_throttle: 10.0
        max_throttle: 100.0
        max_velocity: 20.0

    lateral:
      pure_pursuit:
        look_ahead_distance: 10.0
        wheel_base: 2.987
        max_steering_angle: 0.349066
        smoothing_factor: 0.9

/global_planning:
  ros__parameters:
    debug: false
    visualize: false
    global_path_publish_rate: 1
    local_path_publish_rate: 10
    local_path_length_m: 5.0
    planning_odom_publish_rate: 10
    csv_file_path: src/launch/simple_racing/params/IMS_oval.csv

/autoware_lgsvl_interface:
  ros__parameters:
    max_accel_mps2: 1.0
    max_decel_mps2: -3.0
    gear_shift: true
    

