/**:
  ros__parameters:
    pub_interval_sec: 0.01
    late_threshold_sec: 0.2
    publish_tf: true
    num_gps_subscribers: 1
    num_imu_subscribers: 1
    min_lat_thresh: 0.35
    min_lon_thresh: 0.35
    max_jerk_thresh: 150.0
    max_acc_thresh: 50.0
    max_yaw_rate: 3.0
    heading_cutoff_freq: 10.0
    speed_cutoff_freq: 10.0
    imu_lin_cutoff: 10.0
    imu_ang_cutoff: 10.0
    target_frame: "cg"
