/**:
  ros__parameters:
    rvc:
      control_output_interval_sec: 0.01
      max_front_wheel_angle_rad: 0.349066
      wheelbase_m: 1.05
      track_m: 0.9
      vehicle_weight_kg: 226.8
      turn_left_bias_deg: 0.0
      path_planning_mode: 0 # 0 for internal path planner on timer; 1 for subscribing to RPP
      planning_interval_sec: 0.01 # if path_planning_mode is 0, what's the interval of internal planning

    planner:
      step_interval_sec: 0.01
      lookahead:
        speed_ratio: 1.0
        lateral_error_ratio: 1.0
        lateral_error_ratio_bypass_ttl: [27]
        max_distance_m: 30.0
        min_distance_m: 2.0
      distance_between_waypoints_m: 0.2
      # If the lateral error is above this value, the vehicle will not accelerate
      no_acc_above_lateral_error_m: 1.0
      min_maintained_speed_mps: 2.5

    plugins:
      - "race::InputValidation"
      - "race::PathPlannerPlugin"
      - "race::Timeout"
      - "race::LonControl"
      # - "race::ModelBasedLonControl"
      # - "race::ModelBasedLatControl"
      - "race::PurePursuitController"
      # - "race::LateralCompensation"
      # - "race::LqgControllerPlugin"
      # - "race::CBFLaneKeeping"
      # - "race::GearManagerPlugin"
      - "race::Compliance"
      - "race::Override"
      # - "race::AddSteerBias"
    
    lon_control:
      pid_interval_sec: 0.01
      min_speed_mps: 1.0
      max_speed_mps: 20.0
      throttle_pid:
        kp: 5.0
        ki: 2.0
        kd: 1.0
        min_cmd: -30.0
        max_cmd: 30.0
        min_i: -30.0
        max_i: 30.0
      brake_pid:
        kp: 10.0
        ki: 5.0
        kd: 2.0
        min_cmd: 0.0
        max_cmd: 100.0
        min_i: 0.0
        max_i: 40.0
      brake_deadband_to_speed_ratio: 0.3
      throttle_max_to_speed_ratio: 50.0
      parking_brake_command: 50.0
      lon_control_type: 1 # 0 for throttle/brake control; 1 for speed control
      steady_state_throttle_lookup:
        speed: [0.0, 5.0, 8.0, 12.0]
        throttle: [0.0, 20.0, 25.0, 30.0]

    # model_lon_control:
    #   throttle_scale: 0.95
    #   acc_pid:
    #     kp: 1.0
    #     ki: 0.2
    #     kd: 0.01
    #     min_cmd: -30.0
    #     max_cmd: 5.0
    #     min_i: -10.0
    #     max_i: 5.0
    #   norminal_max_dcc: -5.0
    #   brake_deadband_psi: 100.0
    #   parking_brake_psi: 300.0
    #   stopping_speed: 2.0
    #   output_cutoff_freq: 2.0
    #   lon_control_type: 0
    #   test_mode:
    #     enabled: false
    #     max_brake: 2000.0
    
    # abs:
    #   wheel_radius: 0.29
    #   use_mpc: 1
    #   abs_pid:
    #     kp: 25000.0
    #     ki: 2.4
    #     kd: 0.5
    #     min_cmd: 500.
    #     max_cmd: 4000.
    #     min_i: -1000.
    #     max_i: 3000.
    #     target_slip: 0.1
    #     i_start: 1000.0
    #     trigger: 1000.0
    #   abs_mpc:
    #     K_tao: 15.
    #     moi: 11.9
    #     delay_steps: 0
    #     time_step: 0.05

    # lon_tire_params:
    #   Fz0: 7109.0
    #   pdx1: 1.36527
    #   pdx2: -0.24548
    #   pcx1: 1.49561
    #   pkx1: 46.5687
    #   pkx2: 3.46431e-05
    #   pkx3: 0.0272879
    #   pex1: 0.0
    #   pex2: -0.205265
    #   pex3: 0.261099
    #   phx1: 0.000435981
    #   phx2: -0.000263798
    #   pvx1: -0.0158688
    #   pvx2: 0.0381263
      
    # model_lat_control:
    #   stopping_speed: 2.0
    #   output_cutoff_freq: 0.5
    #   steering_bias_deg: 0.66

    compliance:
      max_throttle_cmd: 100.0
      max_brake_cmd: 100.0
      min_brake_cmd_under_stop: 10.0

    timeout:
      kinematic_state: 2.0
      ttl_command: 2.0
      manual_command: 20.0
      trajectory: 1.0
      output_command: 0.5

    pure_pursuit:
      as_backup: false
      output_cutoff_freq: 2.0
      lookahead_rate_limit: 20.0 # max rate of change of lookahead point, which should be greater or equal to the top vehicle speed

    override:
      throtte_threshold: 1.0
      brake_threshold: 1.0
      steer_threshold_deg: 0.1
      max_manual_speed_mps: 4.0
      steer_decay:
        # the decay follows -0.5 sin(x) + 0.5 in [-pi/2, pi/2] such that the scale goes from 1 to 0.
        start_speed_mps: 5.0 # when higher than this, steering override scale decreases. recommend >= max_manual_speed_mps
        end_speed_mps: 10.0 # when higher than this, steering override is turned off. must > decay_start_speed_mps

    # lateral_compenstation:
    #   min_speed: 2.0
    #   step_interval_sec: 0.01
    #   lateral_pid:
    #     kp: 0.0
    #     ki: 0.0
    #     kd: 0.0
    #     min_cmd: -0.349066
    #     max_cmd: 0.349066
    #     min_i: -0.349066
    #     max_i: 0.349066
    #   ov_ud_steer_lookup:
    #     speed: [0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0]
    #     ratio: [0.0, -0.1, -0.15, -0.25, -0.35, -0.50, -0.51]
    #   max_slip_angle_deg: 6.0

    # gear_manager:
    #   gear_numbers: [1, 2, 3, 4, 5, 6]
    #   min_rpms: [2000.0, 2400.0, 2800.0, 3200.0, 3600.0, 4000.0]
    #   max_rpms: [5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0]
    #   gear_change_wait_sec: 0.5
