/**:
  ros__parameters:
    step_time_period_sec: 0.05
    non_critical_log_time_period_ms: 2000
    use_perception: false
    use_params: true
    start_in_pit: true
    num_start_laps: 0
    cte_threshold: 4.0
    cte_merge_threshold: 2.0
    lap_threshold: 1220.0
    passing_sf_threshold: 590.0
    back_straight:
      start_percentage: 90.0
      end_percentage: 15.0
    manual_overrides:
      auto_enabled: true
      limit_auto_throttle: false
    timeout:
      manual:
        localization_timeout: 0.5
        low_level_fault_timeout: 0.5
        race_control_timeout: 3.0
        input_manual_command_timeout: 1.0
        opp_car_detections_timeout: 0.5
      autonomous:
        localization_timeout: 0.5
        low_level_fault_timeout: 0.5
        race_control_timeout: 3.0
        input_manual_command_timeout: 3.0
        opp_car_detections_timeout:  0.5
    behavior_tree:
      zmq_max_msgs_per_sec: 100
      groot_publisher_port: 1666
      groot_server_port: 1667
      groot_ip_addr: "*"
    ttls:
      left_ttl_index: 2
      right_ttl_index: 9
      optimal_ttl_index: 15
      race_ttl_index: 2
      pit_ttl_index: 27
    speed_limit:
      pit_lane: 30.0
      pit_road: 60.0
      pit_crawl: 10.0
      yellow: 80.0
      green: 100.0
      max: 200.0
    gaps:
      object_detection: 60.0
      attacker_preparing: 33.0
      attacker_attacking: 15.0
      defender_overtaken: 33.0
      defender_vicinity: 13.0
      attacker_done: 18.0
    speed_modifiers:
      overtaking: [20.0, 10.0]
      speed_threshold_for_overtaking: [ 0.0, 100.0]
      catchup: [20.0, 10.0]
      speed_threshold_for_catchup: [ 0.0, 100.0]
    target_speed_profiles:
      enabled: false
      tsp_name: "lvms"
      tsp_segment_names: ["start", "end"]
      lap_percentages: [0.0, 100.0] 
      speed_profiles: [8.0, 10.0]
    scale_factors:
      enabled: true
      lap_percentages: [0.0, 100.0]
      scale_factors: [100.0, 100.0]
    passing_zones:
      enabled: true
      start_percentages: [90.0, 32.7]
      end_percentages: [15.0, 64.0]
      max_speeds: [250.0, 100.0]
    passing_lines:
      percentages: [25.0, 76.5]
