/**:
  ros__parameters:
    fence_safety:
      timeout: 20.0
      trigger_distance: 0.5

    rvc:
      control_output_interval_sec: 0.01
      max_front_wheel_angle_rad: 0.2815999998093
      wheelbase_m: 2.9718
      track_m: 1.6
      vehicle_weight_kg: 700.0
      turn_left_bias_deg: -0.3
      path_planning_mode: 0 # 0 for internal path planner on timer; 1 for subscribing to RPP
      planning_interval_sec: 0.01 # if path_planning_mode is 0, what's the interval of internal planning
    
    planner:
      delay: 0.03 # Computation plus actuator communication delay
      enable_delay_shifting: false
      step_interval_sec: 0.01
      bank_angle_thres: 0.02
      smoothness_factor: 0.02
      lookahead:
        speed_ratio: 0.6
        lateral_error_ratio: 10.0
        lateral_error_ratio_bypass_ttl: [27]
        max_distance_m: 100.0
        min_distance_m: 10.0
      distance_between_waypoints_m: 0.2
      # If the lateral error is above this value, the vehicle will not accelerate
      no_acc_above_lateral_error_m: 2.0
      min_maintained_speed_mps: 5.0

    plugins:
      - "race::InputValidation"
      - "race::PathPlannerPlugin"
      # - "race::Timeout"
      - "race::ModelBasedLonControl"
      # - "race::ModelBasedLatControl"
      - "race::PurePursuitController"
      # - "race::ArtMpcPlugin"
      # - "race::LateralCompensation"
      # - "race::LqgControllerPlugin"
      # - "race::CBFLaneKeeping"
      - "race::GearManagerPlugin"
      - "race::Compliance"
      - "race::Override"
      # - "race::Push2PassHandler"
      # - "race::ABS"
      - "race::AddSteerBias"
      
    model_lon_control:
      # Whether to use controller as backup (if primary controller fails) or primary controller
      as_backup: false
      throttle_scale: 1.0
      acc_pid:
        kp: 1.0
        ki: 0.2
        kd: 0.01
        min_cmd: -30.0
        max_cmd: 5.0
        min_i: -10.0
        max_i: 5.0
      norminal_max_dcc: -5.0
      brake_deadband_psi: 100.0
      parking_brake_psi: 300.0
      stopping_speed: 2.0
      output_cutoff_freq: 2.0
      lon_control_type: 0
      test_mode:
        enabled: false
        max_brake: 2000.0
    
    lon_tire_params:
      Fz0: 7109.0
      pdx1: 1.36527
      pdx2: -0.24548
      pcx1: 1.49561
      pkx1: 46.5687
      pkx2: 3.46431e-05
      pkx3: 0.0272879
      pex1: 0.0
      pex2: -0.205265
      pex3: 0.261099
      phx1: 0.000435981
      phx2: -0.000263798
      pvx1: -0.0158688
      pvx2: 0.0381263
    
    abs:
      wheel_radius: 0.31
      use_mpc: 1
      abs_pid:
        kp: 25000.0
        ki: 2.4
        kd: 0.5
        min_cmd: 500.
        max_cmd: 4000.
        min_i: -1000.
        max_i: 3000.
        target_slip: 0.1
        i_start: 1000.0
        trigger: 1000.0
      abs_mpc:
        K_tao: 15.
        moi: 11.9
        delay_steps: 0
        time_step: 0.05

    model_lat_control:
      stopping_speed: 2.0
      output_cutoff_freq: 0.5
      steering_bias_deg: 0.66

    compliance:
      max_throttle_cmd: 100.0
      max_brake_cmd: 2200.0
      min_brake_cmd_under_stop: 200.0

    timeout:
      kinematic_state: 2.0
      ttl_command: 2.0
      manual_command: 20.0
      trajectory: 1.0
      output_command: 0.5

    pure_pursuit:
      # Whether to use controller as backup (if primary controller fails) or primary controller
      as_backup: false
      output_cutoff_freq: 2.0
      lookahead_rate_limit: 100.0 # max rate of change of lookahead point, which should be greater or equal to the top vehicle speed


    override:
      throtte_threshold: 10.0
      brake_threshold: 5.0
      steer_threshold_deg: 4.0
      max_manual_speed_mps: 100.0
      steer_decay:
        # the decay follows -0.5 sin(x) + 0.5 in [-pi/2, pi/2] such that the scale goes from 1 to 0.
        start_speed_mps: 20.0 # when higher than this, steering override scale decreases. recommend >= max_manual_speed_mps
        end_speed_mps: 30.0 # when higher than this, steering override is turned off. must > decay_start_speed_mps

    lateral_compenstation:
      min_speed: 2.0
      step_interval_sec: 0.01
      lateral_pid:
        kp: 0.0
        ki: 0.0
        kd: 0.0
        min_cmd: -0.349066
        max_cmd: 0.349066
        min_i: -0.349066
        max_i: 0.349066
      ov_ud_steer_lookup:
        speed: [0.0, 20.0, 60.0, 80.0]
        ratio: [0.0, -0.4, -0.5, -0.55]
      max_slip_angle_deg: 6.0

    gear_manager:
      gear_numbers: [1, 2, 3, 4, 5, 6]
      min_rpms: [2000.0, 2400.0, 2800.0, 3200.0, 3600.0, 4000.0]
      max_rpms: [5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0]
      gear_change_wait_sec: 0.5
        
    lqr_config:
      are_max_iter: 1000
      are_error_thresh: 1e-15
      state_performance:
        l_factor: 1.0
        l_const: 1.0
        rc_1_val: 0.2
        l_min: 4.0
        
    
    lqg_config:
      ts: 0.01
      min_speed_mps: 10.0
      max_speed_mps: 100.0
      max_steer_rad: 0.341
      line_error_threshold: 0.001
      initial_state:
        x1: 0.0
        x2: 0.0
        x3: 0.0
        x4: 0.0
      initial_error_cov:
        p0_1: 0.01
        p0_2: 0.01
        p0_3: 0.01
        p0_4: 0.01
      scale_factor:
        x: 2.5
        theta: 0.72
      steady_state_error_correction_multiplier: 1.0 # 1.0 if sensor at front, -1.0 if at rear, 0.0 if at cog
      use_pure_pursuit_params: true
      use_differential_state_params: false

    
    lkf_config: 
      model_error:
        qf_1: 0.01
        qf_2: 0.01
        qf_3: 0.01
        qf_4: 0.01
      measurement_error:
        rf_1: 1.0E-6
        rf_2: 1.0E-7
        rf_3: 1.0E-6
        rf_4: 1.0E-7
    
    lqg_model:
      radius_from_traj_factor: 2 # Must be an integer >= 1 (eg. if 2, half of the trajectory will be considered for radius of curvature calculation)
      # Controller sample time
      ts: 0.01
      # total mass (kg)
      m: 700.0
      mf: 320.0
      mr: 380.0
      # wheel base (meters)
      L: 2.97
      lf: 1.61
      lr: 1.36
      # front tire cornering stiffness
      cf: 598000.0
      # rear tire cornering stiffness
      cr: 632000.0
      # Rotational Moment of Inertia
      iz: 1000.0


    art_mpc:
      max_mpc_invalid_count: 20
      mpc_invalid_count_threshold: 10
      mpc_engage_speed: 2.0
      mpc_disengage_speed: 31.0

    push2passhandler:
      is_active: false

    
    